---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
spec:
  selector:
    matchLabels:
      deployment: hello
  replicas: 3
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
        - name: hello2
          image: "tutum/hello-world:latest"
          ports:
            - name: http
              containerPort: 80
